# Generated by Django 2.2.12 on 2023-09-17 04:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='menor_pago',
            field=otree.db.models.IntegerField(default=10000, null=True),
        ),
    ]
