# Generated by Django 2.2.12 on 2023-09-17 04:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_auto_20230916_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='menor_pago',
        ),
        migrations.AddField(
            model_name='player',
            name='is_menor_pago',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pago_minimo',
            field=otree.db.models.IntegerField(default=10000, null=True),
        ),
    ]
