# Generated by Django 2.2.12 on 2023-10-06 14:55

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_player_data_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pago_base',
            field=otree.db.models.IntegerField(default=20000, null=True),
        ),
    ]
