# Generated by Django 2.2.12 on 2023-09-17 04:24

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_auto_20230916_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pago_base',
            field=otree.db.models.IntegerField(default=20000, null=True),
        ),
    ]
