# Generated by Django 2.2.12 on 2023-09-17 04:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_auto_20230916_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pago_base',
            field=otree.db.models.IntegerField(default=10000, null=True),
        ),
    ]
