# Generated by Django 2.2.12 on 2023-06-05 14:12

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name_app',
            field=otree.db.models.StringField(default='choice', max_length=10000, null=True),
        ),
    ]
