# Generated by Django 2.2.12 on 2023-09-05 14:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0002_player_name_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name_app',
        ),
        migrations.AddField(
            model_name='player',
            name='coin_toss',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='n_investment',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='payoff_amount_app',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='time_choice',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
