# Generated by Django 2.2.12 on 2023-09-16 23:25

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0002_auto_20230916_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name_app',
            field=otree.db.models.StringField(default='choice', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name_app_2_user',
            field=otree.db.models.StringField(default='Invertir o No Invertir', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name_app_n',
            field=otree.db.models.IntegerField(default=4, null=True),
        ),
    ]
