# Generated by Django 2.2.12 on 2023-07-26 08:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('checker1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cnt_mistakes',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='mistakes_checker',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='response_checker',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='time_checker',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
