# Generated by Django 2.2.12 on 2023-09-05 14:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('checker1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='answer_checker',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='time_checker',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
