# Generated by Django 2.2.12 on 2023-08-17 20:00

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_group', to='otree.Session')),
            ],
            options={
                'db_table': 'allocations_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocations_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'allocations_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('name_order_problems', otree.db.models.StringField(max_length=10000, null=True)),
                ('n_order_problems', otree.db.models.StringField(max_length=10000, null=True)),
                ('order_problem_01_a', otree.db.models.IntegerField(null=True)),
                ('order_problem_01_b', otree.db.models.IntegerField(null=True)),
                ('order_problem_02_a', otree.db.models.IntegerField(null=True)),
                ('order_problem_02_b', otree.db.models.IntegerField(null=True)),
                ('order_problem_03_a', otree.db.models.IntegerField(null=True)),
                ('order_problem_03_b', otree.db.models.IntegerField(null=True)),
                ('assetA_problem_01', otree.db.models.IntegerField(null=True)),
                ('assetA_problem_02', otree.db.models.IntegerField(null=True)),
                ('assetA_problem_03', otree.db.models.IntegerField(null=True)),
                ('problem_01_type', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_01_inv_a', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_01_order_a', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_01_order_b', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_01_btnSelected', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_01_btnTime', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_01_sliderSelected', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_01_sliderTime', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_01_sliderInv_a', otree.db.models.IntegerField(null=True)),
                ('problem_01_invCntMistakers', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_01_invMistakes', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_01_invTime', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_01_invVal_a', otree.db.models.IntegerField(null=True)),
                ('problem_01_invVal_b', otree.db.models.IntegerField(null=True)),
                ('problem_01_return_b', otree.db.models.IntegerField(null=True)),
                ('problem_01_expect_return_b', otree.db.models.IntegerField(null=True)),
                ('problem_01_probability_b', otree.db.models.IntegerField(null=True)),
                ('problem_01_var', otree.db.models.IntegerField(null=True)),
                ('problem_02_type', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_02_inv_a', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_02_order_a', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_02_order_b', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_02_btnSelected', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_02_btnTime', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_02_sliderSelected', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_02_sliderTime', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_02_sliderInv_a', otree.db.models.IntegerField(null=True)),
                ('problem_02_invCntMistakers', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_02_invMistakes', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_02_invTime', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_02_invVal_a', otree.db.models.IntegerField(null=True)),
                ('problem_02_invVal_b', otree.db.models.IntegerField(null=True)),
                ('problem_02_return_b', otree.db.models.IntegerField(null=True)),
                ('problem_02_expect_return_b', otree.db.models.IntegerField(null=True)),
                ('problem_02_probability_b', otree.db.models.IntegerField(null=True)),
                ('problem_02_var', otree.db.models.IntegerField(null=True)),
                ('problem_03_type', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_03_inv_a', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_03_order_a', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_03_order_b', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_03_btnSelected', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_03_btnTime', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_03_sliderSelected', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_03_sliderTime', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_03_sliderInv_a', otree.db.models.IntegerField(null=True)),
                ('problem_03_invCntMistakers', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_03_invMistakes', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_03_invTime', otree.db.models.StringField(max_length=10000, null=True)),
                ('problem_03_invVal_a', otree.db.models.IntegerField(null=True)),
                ('problem_03_invVal_b', otree.db.models.IntegerField(null=True)),
                ('problem_03_return_b', otree.db.models.IntegerField(null=True)),
                ('problem_03_expect_return_b', otree.db.models.IntegerField(null=True)),
                ('problem_03_probability_b', otree.db.models.IntegerField(null=True)),
                ('problem_03_var', otree.db.models.IntegerField(null=True)),
                ('name_app', otree.db.models.StringField(default='allocations', max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allocations.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.Subsession')),
            ],
            options={
                'db_table': 'allocations_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocations.Subsession'),
        ),
    ]
