# Generated by Django 2.2.12 on 2023-09-13 19:32

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='problem_0_insurance',
        ),
        migrations.AddField(
            model_name='player',
            name='problem_04_insurance',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
