# Generated by Django 2.2.12 on 2023-10-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='problem_02_expect_return_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_02_insurance',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_02_probability_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_02_return_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_02_risk',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_03_expect_return_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_03_insurance',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_03_probability_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_03_return_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_03_risk',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_04_expect_return_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_04_insurance',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_04_probability_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_04_return_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_04_risk',
        ),
    ]
