# Generated by Django 2.2.12 on 2023-09-12 20:10

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0002_auto_20230906_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='problem_01_var',
        ),
        migrations.AddField(
            model_name='player',
            name='problem_01_insurance',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='problem_01_risk',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
