# Generated by Django 2.2.12 on 2023-10-10 13:56

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0002_auto_20231010_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='problem_01_expect_return_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_01_insurance',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_01_probability_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_01_return_b',
        ),
        migrations.RemoveField(
            model_name='player',
            name='problem_01_risk',
        ),
        migrations.AddField(
            model_name='player',
            name='problem_minus50perc1_risk',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='problem_minus50perc_expect_return_b',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='problem_minus50perc_insurance',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='problem_minus50perc_probability_b',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='problem_minus50perc_return_b',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
