# Generated by Django 2.2.12 on 2023-09-17 02:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0003_auto_20230916_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='amount_cultivo_1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='amount_cultivo_2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='n_scene',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='payoff_amount_app',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
