# Generated by Django 2.2.12 on 2023-10-10 13:58

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0003_auto_20231010_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='problem_minus50perc1_risk',
        ),
        migrations.AddField(
            model_name='player',
            name='problem_minus50perc_risk',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
