# Generated by Django 2.2.12 on 2023-09-17 02:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0004_auto_20230916_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='amount_cultivo_1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='amount_cultivo_2',
        ),
        migrations.AddField(
            model_name='player',
            name='amount_invesment_1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='amount_invesment_2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='n_problem',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
