# Generated by Django 2.2.12 on 2023-09-12 21:44

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0005_auto_20230912_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='problem_02_insurance',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='problem_02_risk',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
