# Generated by Django 2.2.12 on 2023-09-17 02:40

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0005_auto_20230916_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='per_investment_1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='per_investment_2',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
