# Generated by Django 2.2.12 on 2023-09-17 01:50

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='n_scene',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='name_app',
            field=otree.db.models.StringField(default='real', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='name_app_2_user',
            field=otree.db.models.StringField(default='Cultivos', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='name_app_n',
            field=otree.db.models.IntegerField(default=3, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='payoff_amount_app',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
