# Generated by Django 2.2.12 on 2023-09-13 10:36

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='question_1_cultivos',
        ),
        migrations.RemoveField(
            model_name='player',
            name='question_2_cultivos',
        ),
        migrations.RemoveField(
            model_name='player',
            name='question_3_cultivos',
        ),
        migrations.RemoveField(
            model_name='player',
            name='question_4_cultivos',
        ),
        migrations.AddField(
            model_name='player',
            name='question_1_real',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='question_2_real',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='question_3_real',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='question_4_real',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='question_5_real',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
