# Generated by Django 2.2.12 on 2023-09-17 02:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0002_auto_20230916_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='amount_cultivo_1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='amount_cultivo_2',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
