# Generated by Django 2.2.12 on 2023-10-10 02:00

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_group', to='otree.Session')),
            ],
            options={
                'db_table': 'training_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'training_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_01_number', otree.db.models.IntegerField(null=True)),
                ('test_01_answer', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_01_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_02_number', otree.db.models.IntegerField(null=True)),
                ('test_02_answer', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_02_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_03_number', otree.db.models.IntegerField(null=True)),
                ('test_03_answer', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_03_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_04_number', otree.db.models.IntegerField(null=True)),
                ('test_04_answer', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_04_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_05_number_a', otree.db.models.IntegerField(null=True)),
                ('test_05_answer_a', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_05_number_b', otree.db.models.IntegerField(null=True)),
                ('test_05_answer_b', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_05_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_06_number_a', otree.db.models.IntegerField(null=True)),
                ('test_06_answer_a', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_06_number_b', otree.db.models.IntegerField(null=True)),
                ('test_06_answer_b', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_06_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_07_number_a', otree.db.models.IntegerField(null=True)),
                ('test_07_number_b', otree.db.models.IntegerField(null=True)),
                ('test_07_mistakes', otree.db.models.StringField(max_length=10000, null=True)),
                ('test_07_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Subsession')),
            ],
            options={
                'db_table': 'training_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Subsession'),
        ),
    ]
