# Generated by Django 2.2.12 on 2023-09-05 14:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='slider_example',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_03_A_answer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_03_A_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_03_B_answer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_03_B_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_04_A_answer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_04_A_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_04_B_answer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_04_B_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_05_A_answer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_05_A_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_05_B_answer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_05_B_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_05_cardIndex',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_06_cardIndex',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_07_answer',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_07_cardIndex',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_07_payment',
        ),
        migrations.AddField(
            model_name='player',
            name='test_01_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_02_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_03_answer',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_03_number',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_03_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_04_answer',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_04_number',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_04_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_05_answer_a',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_05_answer_b',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_05_number_a',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_05_number_b',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_05_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_06_answer_a',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_06_answer_b',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_06_number_a',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_06_number_b',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='test_06_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='test_01_answer',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='test_02_answer',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
