# Generated by Django 2.2.12 on 2023-09-07 10:28

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20230906_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='test_07_answer_a',
        ),
        migrations.RemoveField(
            model_name='player',
            name='test_07_answer_b',
        ),
        migrations.AddField(
            model_name='player',
            name='test_07_mistakes',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
