# Generated by Django 2.2.12 on 2023-09-16 23:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('choice_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name_app',
            field=otree.db.models.StringField(default='choice_2', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='name_app_2',
            field=otree.db.models.StringField(default='Rentabilidad variable', max_length=10000, null=True),
        ),
    ]
