# Generated by Django 2.2.12 on 2023-09-16 23:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('choice_2', '0002_auto_20230916_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name_app_2',
        ),
        migrations.AddField(
            model_name='player',
            name='name_app_2_user',
            field=otree.db.models.StringField(default='Rentabilidad variable', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='name_app_n',
            field=otree.db.models.IntegerField(default=1, null=True),
        ),
    ]
