# Generated by Django 2.2.12 on 2023-07-26 08:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('icl', '0002_player_name_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='choice_to_pay',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
