# Generated by Django 2.2.12 on 2023-10-10 02:00

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_effort_numbers_group', to='otree.Session')),
            ],
            options={
                'db_table': 'real_effort_numbers_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_effort_numbers_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'real_effort_numbers_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('q1', otree.db.models.StringField(max_length=10000, null=True)),
                ('q1_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('q1_isCorrect', otree.db.models.StringField(max_length=10000, null=True)),
                ('q2', otree.db.models.StringField(max_length=10000, null=True)),
                ('q2_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('q2_isCorrect', otree.db.models.StringField(max_length=10000, null=True)),
                ('q3', otree.db.models.StringField(max_length=10000, null=True)),
                ('q3_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('q3_isCorrect', otree.db.models.StringField(max_length=10000, null=True)),
                ('q4', otree.db.models.StringField(max_length=10000, null=True)),
                ('q4_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('q4_isCorrect', otree.db.models.StringField(max_length=10000, null=True)),
                ('q5', otree.db.models.StringField(max_length=10000, null=True)),
                ('q5_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('q5_isCorrect', otree.db.models.StringField(max_length=10000, null=True)),
                ('q6', otree.db.models.StringField(max_length=10000, null=True)),
                ('q6_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('q6_isCorrect', otree.db.models.StringField(max_length=10000, null=True)),
                ('q7', otree.db.models.StringField(max_length=10000, null=True)),
                ('q7_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('q7_isCorrect', otree.db.models.StringField(max_length=10000, null=True)),
                ('q8', otree.db.models.StringField(max_length=10000, null=True)),
                ('q8_time', otree.db.models.StringField(max_length=10000, null=True)),
                ('q8_isCorrect', otree.db.models.StringField(max_length=10000, null=True)),
                ('cnt_question', otree.db.models.IntegerField(default=1, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='real_effort_numbers.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_effort_numbers_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_effort_numbers_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_effort_numbers.Subsession')),
            ],
            options={
                'db_table': 'real_effort_numbers_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_effort_numbers.Subsession'),
        ),
    ]
