# Generated by Django 2.2.12 on 2023-09-04 12:10

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort_numbers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p1_cnt_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p1_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p1_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p2_cnt_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p2_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p2_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p3_cnt_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p3_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p3_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p4_cnt_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p4_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p4_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p5_cnt_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p5_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p5_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p6_cnt_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p6_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p6_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p7_cnt_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p7_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p7_time',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p8',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p8_cnt_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p8_mistakes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p8_time',
        ),
        migrations.AddField(
            model_name='player',
            name='q1',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q1_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q2',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q2_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q3',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q3_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q4',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q4_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q5',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q5_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q6',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q6_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q7',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q7_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q8',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q8_time',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
