# Generated by Django 2.2.12 on 2023-10-10 02:00

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_age', otree.db.models.IntegerField(null=True)),
                ('q_gender', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_married', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_family', otree.db.models.IntegerField(null=True)),
                ('q_children', otree.db.models.IntegerField(null=True)),
                ('q_workers', otree.db.models.IntegerField(null=True)),
                ('q_educ', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_job', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_income', otree.db.models.IntegerField(null=True)),
                ('q_incomeRange', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_expenses', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_risk', otree.db.models.IntegerField(null=True)),
                ('q_riskList', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_returns', otree.db.models.IntegerField(null=True)),
                ('q_riskImportant', otree.db.models.IntegerField(null=True)),
                ('q_loss', otree.db.models.IntegerField(null=True)),
                ('q_insurance', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_patience', otree.db.models.IntegerField(null=True)),
                ('q_hectares', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_farminc', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_crops', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_cropTypes', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_cropsImp_1', otree.db.models.IntegerField(null=True)),
                ('q_cropsImp_2', otree.db.models.IntegerField(null=True)),
                ('q_cropsImp_3', otree.db.models.IntegerField(null=True)),
                ('q_cropsImp_4', otree.db.models.IntegerField(null=True)),
                ('q_cropsImp_5', otree.db.models.IntegerField(null=True)),
                ('q_cropsImp_6', otree.db.models.IntegerField(null=True)),
                ('q_cropsLoss', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_savings', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_protection_1', otree.db.models.IntegerField(null=True)),
                ('q_protection_2', otree.db.models.IntegerField(null=True)),
                ('q_protection_3', otree.db.models.IntegerField(null=True)),
                ('q_protection_4', otree.db.models.IntegerField(null=True)),
                ('q_protection_5', otree.db.models.IntegerField(null=True)),
                ('q_protection_6', otree.db.models.IntegerField(null=True)),
                ('q_climate', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_events', otree.db.models.StringField(max_length=10000, null=True)),
                ('q_measures', otree.db.models.StringField(max_length=10000, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Subsession')),
            ],
            options={
                'db_table': 'survey_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Subsession'),
        ),
    ]
