# Generated by Django 2.2.12 on 2023-08-17 20:00

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_group', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'survey_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('p_age', otree.db.models.IntegerField(null=True, verbose_name='1. Edad')),
                ('p_sex', otree.db.models.IntegerField(choices=[[0, 'Hombre'], [1, 'Mujer'], [2, 'Otro']], null=True, verbose_name='2. ¿Con qué género se identifica?')),
                ('p_married', otree.db.models.IntegerField(choices=[[1, 'Unión libre'], [2, 'Casado (a)'], [3, 'Viudo (a)'], [4, 'Soltero (a)'], [5, 'Divorciado (a)/Separado(a)']], null=True, verbose_name='3. Estado civil')),
                ('p_family', otree.db.models.IntegerField(null=True, verbose_name='4. ¿Número de miembros del hogar?')),
                ('p_children', otree.db.models.IntegerField(null=True, verbose_name='5. ¿Número de hijos?')),
                ('p_workers', otree.db.models.IntegerField(null=True, verbose_name='6. ¿Número de personas que contribuyen a los ingresos del hogar?')),
                ('p_educ', otree.db.models.IntegerField(choices=[[1, 'Ninguno'], [2, 'Primaria'], [3, 'Bachillerato'], [4, 'Técnico o Tecnólogo'], [5, 'Pregrado'], [6, 'Posgrado (Especialización, Maestría, Doctorado)']], null=True, verbose_name='7. ¿Cuál es el nivel educativo más alto que cursó o está cursando?')),
                ('p_job', otree.db.models.IntegerField(choices=[[1, 'Solo estudio'], [2, 'Desempleado'], [3, 'Empleado a jornada completa'], [4, 'Empleado a tiempo parcial'], [5, 'Trabajador independiente'], [6, 'Trabajador no remunerado (por ejemplo: ama de casa, empresa familiar)'], [7, 'Retirado/pensionado'], [8, 'Otro'], [9, 'No sabe']], null=True, verbose_name='8. ¿Cuál es su situación laboral actual?')),
                ('p_inc', otree.db.models.IntegerField(choices=[[1, 'Menos de $ 300.000'], [2, 'Entre $ 300.000 - $ 600.000'], [3, 'Entre $ 600.000 - $ 900.000'], [4, 'Entre $ 900.000 - $ 1.200.000'], [5, 'Entre $ 1.200.000 - $ 1.500.000'], [6, 'Mayor a $ 1.500.000']], null=True, verbose_name='9. ¿Cuál es el rango de su ingreso mensual?')),
                ('p_inc1', otree.db.models.CurrencyField(null=True, verbose_name='10. ¿Cuánto es su ingreso mensual?')),
                ('p_expenses', otree.db.models.IntegerField(choices=[[1, 'Mayores'], [2, 'Menores'], [3, 'Iguales']], null=True, verbose_name='11. En el último mes los gastos del hogar frente a sus ingresos han sido:')),
                ('p_dexpenses', otree.db.models.IntegerField(choices=[[1, 'Endeudarse'], [2, 'Vender un activo'], [3, 'Disponer de los ahorros'], [4, 'Pedir ayuda a un familiar'], [5, 'Pedir ayuda a un conocido del barrio-vereda'], [6, 'No hubo tales meses']], null=True, verbose_name='12. En los meses en que los gastos del hogar han superado los ingresos, ¿qué han hecho para cubrir esta diferencia?')),
                ('p_group', otree.db.models.IntegerField(choices=[[1, 'Cooperativas'], [2, 'Gremios'], [3, 'Asociación de productores'], [4, 'Centros de investigación'], [5, 'Organizaciones comunitarias (consejo comunitario, asociación u organización étnica, de mujeres, de ancianos o de jóvenes)'], [6, 'No pertenece a ninguna asociación'], [7, 'No sabe / No responde']], null=True, verbose_name='13. Actualmente el productor pertenece a alguna de las siguientes asociaciones:')),
                ('p_insurance', otree.db.models.IntegerField(choices=[[1, 'Sí'], [2, 'No'], [3, 'No sabe / No responde']], null=True, verbose_name='14. Durante los últimos 12 meses, usted o algún miembro de su hogar ha contratado o renovado algún seguro de vida, vehículo, terremoto, robo, desempleo u otro seguro, en forma voluntaria?')),
                ('p_savings', otree.db.models.IntegerField(choices=[[1, 'Sí'], [2, 'No'], [3, 'No sabe / No responde']], null=True, verbose_name='15. ¿Considera que cuando deje de trabajar podrá solventar los gastos de su hogar con sus ahorros para la vejez?')),
                ('p_pension', otree.db.models.IntegerField(choices=[[1, 'Aportando en un fondo de pensiones obligatorias'], [2, 'Aportando en un fondo de pensiones voluntarias (por ejemplo, BEPS)'], [3, 'Ahorrando'], [4, 'Haciendo inversiones'], [5, 'Pagando un seguro por su cuenta'], [6, 'Preparando a sus hijos para que puedan ayudarlo en su vejez'], [7, 'Nada'], [8, 'No sabe / No responde']], null=True, verbose_name='16. ¿Qué está haciendo USTED para mantenerse económicamente en la vejez?')),
                ('p_events', otree.db.models.IntegerField(choices=[[1, 'Enfrentamientos entre grupos armados'], [2, 'Atentados terroristas'], [3, 'Inundaciones'], [4, 'Terremotos/Temblores'], [5, 'Más lluvia de lo habitual'], [6, 'Sequías'], [7, 'Otros desastres naturales'], [8, 'Ningún problema'], [9, 'No sabe / No responde']], null=True, verbose_name='17. Durante los últimos 12 meses, ¿en esta zona o vecindario se presentaron algunos de los siguientes problemas?')),
                ('p_climate', otree.db.models.IntegerField(choices=[[1, 'Ahorro'], [2, 'Endeudamiento'], [3, 'Inversión'], [4, 'No tiene en cuenta los cambios de clima']], null=True, verbose_name='18. ¿Para cuál de las siguientes decisiones tiene en cuenta el cambio del clima?')),
                ('p_season', otree.db.models.IntegerField(choices=[[1, 'Invierno'], [2, 'Verano']], null=True, verbose_name='19. ¿Qué estación del año prefiere?')),
                ('p_precautions', otree.db.models.StringField(max_length=10000, null=True, verbose_name='20. ¿Qué medidas preventivas toma para que los cambios de climas no afecten sus ingresos?')),
                ('p_climate1', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Nos estamos acercando al límite de la cantidad de personas que la Tierra puede sostener.')),
                ('p_climate2', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Los seres humanos tienen el derecho de modificar el medio ambiente natural para satisfacer sus necesidades.')),
                ('p_climate3', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Cuando los seres humanos interfieren con la naturaleza, a menudo producen consecuencias desastrosas.')),
                ('p_climate4', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='El ingenio humano asegurará que no hagamos la Tierra inhabitable.')),
                ('p_climate5', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Los seres humanos están abusando gravemente de la Tierra.')),
                ('p_climate6', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='La Tierra tiene abundantes recursos naturales si simplemente aprendemos cómo usarlos.')),
                ('p_climate7', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Las plantas y los animales tienen tanto derecho a existir como los humanos.')),
                ('p_climate8', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='El equilibrio de la naturaleza es lo suficientemente fuerte para hacer frente a los impactos de los países industrializados modernos.')),
                ('p_climate9', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='A pesar de nuestras habilidades especiales, los seres humanos todavía estamos sujetos a las leyes de la naturaleza.')),
                ('p_climate10', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='La llamada crisis ecológica que enfrenta la humanidad ha sido ampliamente exagerada.')),
                ('p_climate11', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='La Tierra es como una nave espacial con un espacio y recursos muy limitados.')),
                ('p_climate12', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Los seres humanos estaban destinados a gobernar sobre el resto de la naturaleza.')),
                ('p_climate13', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='El equilibrio de la naturaleza es muy delicado y fácilmente perturbable.')),
                ('p_climate14', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Los seres humanos eventualmente aprenderán lo suficiente sobre cómo funciona la naturaleza para poder controlarla.')),
                ('p_climate15', otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Si las cosas siguen su curso actual, pronto experimentaremos una enorme catástrofe ambiental.')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Subsession')),
            ],
            options={
                'db_table': 'survey_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Subsession'),
        ),
    ]
