# Generated by Django 2.2.12 on 2023-07-26 08:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ocu_father',
            field=otree.db.models.IntegerField(choices=[[1, 'Empleado con cargo como director o gerente general'], [2, 'Empleado de nivel auxiliar o administrativo'], [3, 'Empleado de nivel directivo'], [4, 'Empleado de nivel técnico o profesional'], [5, 'Empleado obrero u operario'], [6, 'Empresario'], [7, 'Pequeño empresario'], [8, 'Profesional independiente'], [9, 'Trabajador por cuenta propia'], [10, 'Hogar'], [11, 'Pensionado'], [12, 'Desempleado'], [13, 'Otra actividad u ocupación']], null=True, verbose_name='8. ¿Cuál es su ocupación u oficio?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_inc',
            field=otree.db.models.IntegerField(choices=[[1, 'Menos de $ 300.000'], [2, 'Entre $ 300.000 - $ 600.000'], [3, 'Entre $ 600.000 - $ 900.000'], [4, 'Entre $ 900.000 - $ 1.200.000'], [5, 'Entre $ 1.200.000 - $ 1.500.000'], [6, 'Mayor a $ 1.500.000']], null=True, verbose_name='5.1 ¿Cuál es el rango de su ingreso mensual?'),
        ),
    ]
