# Generated by Django 2.2.12 on 2023-06-02 13:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20230602_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ocu_father',
            field=otree.db.models.IntegerField(choices=[[1, 'Empleado con cargo como director o gerente general'], [2, 'Empleado de nivel auxiliar o administrativo'], [3, 'Empleado de nivel directivo'], [4, 'Empleado de nivel técnico o profesional'], [5, 'Empleado obrero u operario'], [6, 'Empresario'], [7, 'Pequeño empresario'], [8, 'Profesional independiente'], [9, 'Trabajador por cuenta propia'], [10, 'Hogar'], [11, 'Pensionado'], [12, 'Desempleado'], [13, 'Otra actividad u ocupación']], null=True, verbose_name='8. Ocupación u oficio del padre'),
        ),
    ]
