# Generated by Django 2.2.12 on 2023-09-21 23:29

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20230921_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_married',
        ),
        migrations.AddField(
            model_name='player',
            name='q_children',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_family',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_workers',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_family',
            field=otree.db.models.IntegerField(null=True, verbose_name=''),
        ),
    ]
