# Generated by Django 2.2.12 on 2023-09-21 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20230921_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_children',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p_family',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p_workers',
        ),
    ]
