# Generated by Django 2.2.12 on 2023-09-05 14:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20230602_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='ocu_father',
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate',
            field=otree.db.models.IntegerField(choices=[[1, 'Ahorro'], [2, 'Endeudamiento'], [3, 'Inversión'], [4, 'No tiene en cuenta los cambios de clima']], null=True, verbose_name='18. ¿Para cuál de las siguientes decisiones tiene en cuenta el cambio del clima?'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate1',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Nos estamos acercando al límite de la cantidad de personas que la Tierra puede sostener.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate10',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='La llamada crisis ecológica que enfrenta la humanidad ha sido ampliamente exagerada.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate11',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='La Tierra es como una nave espacial con un espacio y recursos muy limitados.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate12',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Los seres humanos estaban destinados a gobernar sobre el resto de la naturaleza.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate13',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='El equilibrio de la naturaleza es muy delicado y fácilmente perturbable.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate14',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Los seres humanos eventualmente aprenderán lo suficiente sobre cómo funciona la naturaleza para poder controlarla.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate15',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Si las cosas siguen su curso actual, pronto experimentaremos una enorme catástrofe ambiental.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate2',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Los seres humanos tienen el derecho de modificar el medio ambiente natural para satisfacer sus necesidades.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate3',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Cuando los seres humanos interfieren con la naturaleza, a menudo producen consecuencias desastrosas.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate4',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='El ingenio humano asegurará que no hagamos la Tierra inhabitable.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate5',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Los seres humanos están abusando gravemente de la Tierra.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate6',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='La Tierra tiene abundantes recursos naturales si simplemente aprendemos cómo usarlos.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate7',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Las plantas y los animales tienen tanto derecho a existir como los humanos.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate8',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='El equilibrio de la naturaleza es lo suficientemente fuerte para hacer frente a los impactos de los países industrializados modernos.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_climate9',
            field=otree.db.models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='A pesar de nuestras habilidades especiales, los seres humanos todavía estamos sujetos a las leyes de la naturaleza.'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_dexpenses',
            field=otree.db.models.IntegerField(choices=[[1, 'Endeudarse'], [2, 'Vender un activo'], [3, 'Disponer de los ahorros'], [4, 'Pedir ayuda a un familiar'], [5, 'Pedir ayuda a un conocido del barrio-vereda'], [6, 'No hubo tales meses']], null=True, verbose_name='12. En los meses en que los gastos del hogar han superado los ingresos, ¿qué han hecho para cubrir esta diferencia?'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_events',
            field=otree.db.models.IntegerField(choices=[[1, 'Enfrentamientos entre grupos armados'], [2, 'Atentados terroristas'], [3, 'Inundaciones'], [4, 'Terremotos/Temblores'], [5, 'Más lluvia de lo habitual'], [6, 'Sequías'], [7, 'Otros desastres naturales'], [8, 'Ningún problema'], [9, 'No sabe / No responde']], null=True, verbose_name='17. Durante los últimos 12 meses, ¿en esta zona o vecindario se presentaron algunos de los siguientes problemas?'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_expenses',
            field=otree.db.models.IntegerField(choices=[[1, 'Mayores'], [2, 'Menores'], [3, 'Iguales']], null=True, verbose_name='11. En el último mes los gastos del hogar frente a sus ingresos han sido:'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_family',
            field=otree.db.models.IntegerField(null=True, verbose_name='4. ¿Número de miembros del hogar?'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_group',
            field=otree.db.models.IntegerField(choices=[[1, 'Cooperativas'], [2, 'Gremios'], [3, 'Asociación de productores'], [4, 'Centros de investigación'], [5, 'Organizaciones comunitarias (consejo comunitario, asociación u organización étnica, de mujeres, de ancianos o de jóvenes)'], [6, 'No pertenece a ninguna asociación'], [7, 'No sabe / No responde']], null=True, verbose_name='13. Actualmente el productor pertenece a alguna de las siguientes asociaciones:'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_insurance',
            field=otree.db.models.IntegerField(choices=[[1, 'Sí'], [2, 'No'], [3, 'No sabe / No responde']], null=True, verbose_name='14. Durante los últimos 12 meses, usted o algún miembro de su hogar ha contratado o renovado algún seguro de vida, vehículo, terremoto, robo, desempleo u otro seguro, en forma voluntaria?'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_pension',
            field=otree.db.models.IntegerField(choices=[[1, 'Aportando en un fondo de pensiones obligatorias'], [2, 'Aportando en un fondo de pensiones voluntarias (por ejemplo, BEPS)'], [3, 'Ahorrando'], [4, 'Haciendo inversiones'], [5, 'Pagando un seguro por su cuenta'], [6, 'Preparando a sus hijos para que puedan ayudarlo en su vejez'], [7, 'Nada'], [8, 'No sabe / No responde']], null=True, verbose_name='16. ¿Qué está haciendo USTED para mantenerse económicamente en la vejez?'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_precautions',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='20. ¿Qué medidas preventivas toma para que los cambios de climas no afecten sus ingresos?'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_savings',
            field=otree.db.models.IntegerField(choices=[[1, 'Sí'], [2, 'No'], [3, 'No sabe / No responde']], null=True, verbose_name='15. ¿Considera que cuando deje de trabajar podrá solventar los gastos de su hogar con sus ahorros para la vejez?'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_season',
            field=otree.db.models.IntegerField(choices=[[1, 'Invierno'], [2, 'Verano']], null=True, verbose_name='19. ¿Qué estación del año prefiere?'),
        ),
        migrations.AddField(
            model_name='player',
            name='p_workers',
            field=otree.db.models.IntegerField(null=True, verbose_name='6. ¿Número de personas que contribuyen a los ingresos del hogar?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_age',
            field=otree.db.models.IntegerField(null=True, verbose_name='1. Edad'),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_children',
            field=otree.db.models.IntegerField(null=True, verbose_name='5. ¿Número de hijos?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_educ',
            field=otree.db.models.IntegerField(choices=[[1, 'Ninguno'], [2, 'Primaria'], [3, 'Bachillerato'], [4, 'Técnico o Tecnólogo'], [5, 'Pregrado'], [6, 'Posgrado (Especialización, Maestría, Doctorado)']], null=True, verbose_name='7. ¿Cuál es el nivel educativo más alto que cursó o está cursando?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_inc',
            field=otree.db.models.IntegerField(choices=[[1, 'Menos de $ 300.000'], [2, 'Entre $ 300.000 - $ 600.000'], [3, 'Entre $ 600.000 - $ 900.000'], [4, 'Entre $ 900.000 - $ 1.200.000'], [5, 'Entre $ 1.200.000 - $ 1.500.000'], [6, 'Mayor a $ 1.500.000']], null=True, verbose_name='9. ¿Cuál es el rango de su ingreso mensual?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_inc1',
            field=otree.db.models.CurrencyField(null=True, verbose_name='10. ¿Cuánto es su ingreso mensual?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_job',
            field=otree.db.models.IntegerField(choices=[[1, 'Solo estudio'], [2, 'Desempleado'], [3, 'Empleado a jornada completa'], [4, 'Empleado a tiempo parcial'], [5, 'Trabajador independiente'], [6, 'Trabajador no remunerado (por ejemplo: ama de casa, empresa familiar)'], [7, 'Retirado/pensionado'], [8, 'Otro'], [9, 'No sabe']], null=True, verbose_name='8. ¿Cuál es su situación laboral actual?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_married',
            field=otree.db.models.IntegerField(choices=[[1, 'Unión libre'], [2, 'Casado (a)'], [3, 'Viudo (a)'], [4, 'Soltero (a)'], [5, 'Divorciado (a)/Separado(a)']], null=True, verbose_name='3. Estado civil'),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_sex',
            field=otree.db.models.IntegerField(choices=[[0, 'Hombre'], [1, 'Mujer'], [2, 'Otro']], null=True, verbose_name='2. ¿Con qué género se identifica?'),
        ),
    ]
