# Generated by Django 2.2.12 on 2023-09-21 23:44

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20230921_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q_educ',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_income',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_job',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
