# Generated by Django 2.2.12 on 2023-09-21 23:45

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20230921_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q_incomeRange',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
