# Generated by Django 2.2.12 on 2023-09-21 23:52

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_player_q_incomerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q_expenses',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
