# Generated by Django 2.2.12 on 2023-09-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_player_q_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_educ',
        ),
    ]
