# Generated by Django 2.2.12 on 2023-09-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_remove_player_p_educ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_job',
        ),
    ]
