# Generated by Django 2.2.12 on 2023-09-22 00:01

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_remove_player_p_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='p_expenses',
            field=otree.db.models.IntegerField(choices=[[1, 'Mayores'], [2, 'Menores'], [3, 'Iguales']], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_inc',
            field=otree.db.models.CurrencyField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_inc1',
            field=otree.db.models.IntegerField(choices=[[1, 'Menos de $ 300.000'], [2, 'Entre $ 300.000 - $ 600.000'], [3, 'Entre $ 600.000 - $ 900.000'], [4, 'Entre $ 900.000 - $ 1.200.000'], [5, 'Entre $ 1.200.000 - $ 1.500.000'], [6, 'Mayor a $ 1.500.000'], [7, 'Otro / Ninguno']], null=True, verbose_name=''),
        ),
    ]
