# Generated by Django 2.2.12 on 2023-09-22 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20230921_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_expenses',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p_inc',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p_inc1',
        ),
    ]
