# Generated by Django 2.2.12 on 2023-09-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_player_risk_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_risk',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p_risk1',
        ),
    ]
