# Generated by Django 2.2.12 on 2023-09-23 22:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20230922_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q_returns',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='p_returns',
            field=otree.db.models.IntegerField(null=True, verbose_name=' (0 - significa que no es importante, y 10 - significa que es muy importante)'),
        ),
    ]
