# Generated by Django 2.2.12 on 2023-09-23 23:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20230923_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_returns',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q_risk_list',
        ),
        migrations.AddField(
            model_name='player',
            name='q_riskImportant',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_riskList',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
