# Generated by Django 2.2.12 on 2023-09-23 23:06

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_player_q_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q_insurance',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_patience',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
