# Generated by Django 2.2.12 on 2023-09-23 23:11

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20230923_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='p_risk2',
            field=otree.db.models.IntegerField(null=True, verbose_name='Cuando decide invertir,  (0 - significa que no es importante, y 10 - significa que es muy importante)'),
        ),
    ]
