# Generated by Django 2.2.12 on 2023-09-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_auto_20230923_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_loss',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p_risk2',
        ),
    ]
