# Generated by Django 2.2.12 on 2023-09-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20230923_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_insurance',
        ),
        migrations.RemoveField(
            model_name='player',
            name='p_patience',
        ),
    ]
