# Generated by Django 2.2.12 on 2023-09-23 23:41

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_auto_20230923_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_farminc',
        ),
        migrations.AddField(
            model_name='player',
            name='q_crops',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
