# Generated by Django 2.2.12 on 2023-09-23 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_auto_20230923_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_crops',
        ),
    ]
