# Generated by Django 2.2.12 on 2023-09-23 23:52

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_remove_player_p_crops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='p_crops1',
            field=otree.db.models.IntegerField(choices=[[1]], null=True, verbose_name='¿Qué tipo de cultivos siembró el año pasado? (Puede marcar varias opciones)'),
        ),
    ]
