# Generated by Django 2.2.12 on 2023-09-24 15:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_remove_player_p_crops1'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q_cropsImp_1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_cropsImp_2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_cropsImp_3',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_cropsImp_4',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_cropsImp_5',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_cropsImp_6',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
