# Generated by Django 2.2.12 on 2023-09-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_player_q_cropsloss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_crops3',
        ),
    ]
