# Generated by Django 2.2.12 on 2023-09-24 16:44

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0033_remove_player_p_crops3'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q_savings',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
