# Generated by Django 2.2.12 on 2023-09-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0035_auto_20230924_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_savings',
        ),
    ]
