# Generated by Django 2.2.12 on 2023-09-24 16:54

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0036_remove_player_p_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q_protection_1',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_protection_2',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_protection_3',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_protection_4',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_protection_5',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_protection_6',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
