# Generated by Django 2.2.12 on 2023-09-24 16:59

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0037_auto_20230924_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q_climate',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q_events',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
