# Generated by Django 2.2.12 on 2023-09-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0039_auto_20230924_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_climate',
        ),
    ]
