# Generated by Django 2.2.12 on 2023-09-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0040_remove_player_p_climate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_events',
        ),
    ]
