# Generated by Django 2.2.12 on 2023-09-24 17:07

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0041_remove_player_p_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q_measuers',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
