# Generated by Django 2.2.12 on 2023-09-24 17:07

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0042_player_q_measuers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='p_measures',
            field=otree.db.models.IntegerField(choices=[[1]], null=True, verbose_name='¿Si estos eventos afectarán negativamente a su hogar, qué medidas tomaría?'),
        ),
    ]
