# Generated by Django 2.2.12 on 2023-09-24 17:09

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0043_auto_20230924_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='p_measures',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q_measuers',
        ),
        migrations.AddField(
            model_name='player',
            name='q_measures',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
